sudo: required
dist: trusty
language: cpp

# notifications:
#   email:
#     recipients:
#       - a@b.com

compiler:
  - clang
  - gcc

env:
 - BUILDTYPE=DEBUG
 - BUILDTYPE=RELEASE
 - BUILDTYPE=RELWITHDEBINFO
 # - BUILDTYPE=ASAN           # Address sanitizer
 # - BUILDTYPE=UBSAN          # Undefined-behaviour sanitizer
 # - BUILDTYPE=ANALYZE        # Use scan_build, which builds with Clang's static analyzer

matrix:
 exclude:
   # ATM, GCC doesn't implement the memory sanitizer
   - compiler: gcc
     env: BUILDTYPE=MSAN
#    - compiler: gcc
#      env: BUILDTYPE="ANALYZE"

install:
  # - if [ "$CXX"       == "g++"            ]; then export CXX="g++-4.9"     CC="gcc-4.9"   ; fi
  # - if [ "$CXX"       == "clang++"        ]; then export CXX="clang++-3.6" CC="clang-3.6" ; fi
  - if [ "$BUILDTYPE" == "DEBUG"          ]; then export CMAKE_BUILD_TYPE="DEBUG"         ; export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                                           ; fi
  - if [ "$BUILDTYPE" == "RELEASE"        ]; then export CMAKE_BUILD_TYPE="RELEASE"       ; export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                                           ; fi
  - if [ "$BUILDTYPE" == "RELWITHDEBINFO" ]; then export CMAKE_BUILD_TYPE="RELWITHDEBINFO"; export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                                           ; fi
  # - if [ "$BUILDTYPE" == "ASAN"           ]; then export CMAKE_BUILD_TYPE="RELEASE"       ; export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fsanitize=address -fno-omit-frame-pointer"; fi
  # - if [ "$BUILDTYPE" == "UBSAN"          ]; then export CMAKE_BUILD_TYPE="RELEASE"       ; export CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fsanitize=undefined                      "; fi
  # - if [ "$BUILDTYPE" == "ANALYZE"        ]; then export CMAKE_BUILD_TYPE="RELEASE"       ; export WRAPPER="scan_build-3.6 " ; fi else export WRAPPER=" "                         ; fi

# addons:
#   apt:
#     sources:
#     - kalakris-cmake
#     - llvm-toolchain-precise-3.6
#     - ubuntu-toolchain-r-test
#     packages:
#     - clang-3.6
#     - cmake
#     - gcc-4.9
#     - g++-4.9
#     - ninja-build

before_script:
  - mkdir build && cd build
  - cmake "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" "-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}" ..
  - cd $TRAVIS_BUILD_DIR

script: make -k -C build && build/build-test
