site_name: clone-tools
theme: readthedocs

extra_css: [mkdocs_extra.css]

pages:
- Home      : index.md
- Reference :
  - clone_ptr : reference/clone_ptr.md
  - utility   : reference/utility/index.md
- About     : about.md


# markdown_extensions:
#   - fenced_code
